### ISSUE TITLE
Old dfx version hardcoded

### ISSUE THREAD

**Issue by vporton** [canscale/CanDB#21]
Why is old `dfx` version `0.11.2` hardcoded in `examples/multiCanister/simpleMultiCanister/dfx.json`?

It prevents me to compile it with current `dfx`. As a workaround, I will fork `canscale/CanDB` to my own version without specified version.

**Comment by q-uint** [comment]
Hi @vporton, you can use the `dfx cache` to switch versions.

**Comment by ByronBecker** [comment]
Hey @vporton, thanks for catching this and filing an issue - that example is currently out of date. I recommend checking out the [documentation](https://docs.google.com/document/d/1HrJuX9l-UL3rWbPDF-PXdVjG6oHy9h6sIhHgVqROFXE/mobilebasic#heading=h.7vct6zv0pokg) and [the hello candb tutorial](https://docs.google.com/document/d/1vCrJHTEw3co3nHWNUDvKPy5N2mI2v83_Rbo-eSx6aHQ/).

I'm traveling right now, but will update this example when I get back next week.

**Comment by ByronBecker** [comment]
Resolved in #22
